# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    #config.vm.network "private_network", type: "dhcp"
    config.vm.network "forwarded_port", guest: 80, guest_ip: "10.0.2.15", host: 8080, host_ip: "127.0.0.1"
    #config.vm.synced_folder ".", "/var/www/html"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
end
    config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install apache2 -y
    SHELL
end
